{% set version = "2.1.2" %}

package:
  name: gflags
  version: {{ version }}

source:
  fn: gflags-{{ version }}.tar.gz
  url: https://github.com/gflags/gflags/archive/v{{ version }}.tar.gz
  sha1: 8bdbade9d041339dc14b4ab426e2354a5af38478

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libgflags.dylib)            # [osx]
    - exit $(test -f ${PREFIX}/lib/libgflags_nothreads.dylib)  # [osx]
    - exit $(test -f ${PREFIX}/lib/libgflags.so)               # [linux]
    - exit $(test -f ${PREFIX}/lib/libgflags_nothreads.so)     # [linux]

about:
  home: https://github.com/gflags/gflags
  license: BSD 3-Clause
  license_file: COPYING.txt
  summary: A C++ library that implements commandline flags processing.

extra:
  recipe-maintainers:
    - jakirkham
