{% set name = "gflags" %}
{% set version = "2.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f619a51371f41c0ad6837b2a98af9d4643b3371015d873887f7e8d3237320b2f

build:
  number: 1
  run_exports:
    # seems to change SONAME every minor version
    # https://abi-laboratory.pro/tracker/timeline/gflags/
    - {{ pin_subpackage('gflags', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [not win64]
  host:
    - msinttypes  # [win and py<35]

test:
  commands:
    - test -f ${PREFIX}/lib/libgflags.dylib                           # [osx]
    - test -f ${PREFIX}/lib/libgflags_nothreads.dylib                 # [osx]
    - test -f ${PREFIX}/lib/libgflags.so                              # [linux]
    - test -f ${PREFIX}/lib/libgflags_nothreads.so                    # [linux]
    - test -f ${PREFIX}/lib/libgflags.a                               # [not win]
    - test -f ${PREFIX}/lib/libgflags_nothreads.a                     # [not win]
    - if not exist %PREFIX%\\Library\\bin\\gflags.dll exit 1          # [win]
    - if not exist %PREFIX%\\Library\\lib\\gflags.lib exit 1          # [win]
    - if not exist %PREFIX%\\Library\\lib\\gflags_static.lib exit 1   # [win]


about:
  home: https://github.com/gflags/gflags
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: A C++ library that implements commandline flags processing.
  description: |
    gflags are Commandline flags that Users specify on the command line when they run an executable.
  doc_url: https://gflags.github.io/gflags
  dev_url: https://github.com/gflags/gflags

extra:
  recipe-maintainers:
    - jakirkham
    - wesm
