travis:
  secure:
    BINSTAR_TOKEN: j8MhQXRb9o8Zk1stiUIPFqddLirXBZC2HGe/SZyIDEMEdiofG1CrDOkmkN2eBb509rQPHMcEg9bwFlxPYR37I6AD1MjSrRwmpuodl+RRqAHttlN3Ulmbpa0V/bbQ/SL5JOdSlgQQD9yvOLQAyzsjn0yoZGU6MNaf9lEkcs8XuBz/VfRd6VZ7m0JIhloGUB26Hj9GedIP9ZznHe/Y/1tp3lovKKFngKCYlILF6viWGhlWOUX38TEoKoefA5/X0MoAlxql+iBgA11sxzDCo2f7daFk/gNrX2T42b8ywkN9nDiArm3xfzQ8eUqNRCqbXRcAtwkFzFUot0v9vuy+YPK4eJ8h64RiGvXQ0bVED3QCpvK27m0H2dBKLVSrcFHVhhnIWx+Mr477pEyQUCKApW0eDF2HJGljb5GR1JVSObPDih4UI5GNS9bRIl2ECgDySBIRFQ3VLTw3Q5SaEeV6KtoilS+e2lpFVvCaQwq3DbP0iJ+l5XNFfSpe+W4iBefgoiPknInOeuV8bDdTrVmEC+NLfuH0l9d6PpQorqUbVlhaZ7DL+zXgfEcDLGVfVLxVwylW98q3Qe8msIIY9iECoMCFcF2yl7TnTRNXm2arEu9m/a7jnF97Pl22rsFVDH2BLOZbia4KK5ZwBEN9IxgMtwYFeOMk/fBA8dPPo7lxyG9oeqo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
